- name: Take snapshot of a VM using quiesce and memory flag on
  vmware_guest_snapshot:
    hostname: 192.168.1.209
    username: administrator@vsphere.local
    password: vmware
    name: dummy_vm
    state: present
    snapshot_name: dummy_vm_snap_0001
    quiesce: True
    memory_dump: True
  delegate_to: localhost
