- name: Remove all snapshots of a VM
  vmware_guest_snapshot:
    hostname: 192.168.1.209
    username: administrator@vsphere.local
    password: vmware
    datacenter: datacenter_name
    folder: /myfolder
    name: dummy_vm
    state: remove_all
  delegate_to: localhost
