- name: Remove a snapshot
  vmware_guest_snapshot:
    hostname: 192.168.1.209
    username: administrator@vsphere.local
    password: vmware
    name: dummy_vm
    datacenter: datacenter_name
    folder: /myfolder
    state: remove
    snapshot_name: snap1
  delegate_to: localhost
