- name: Remove a snapshot and snapshot subtree
  vmware_guest_snapshot:
    hostname: 192.168.1.209
    username: administrator@vsphere.local
    password: vmware
    name: dummy_vm
    state: remove
    remove_children: True
    snapshot_name: snap1
  delegate_to: localhost
