- name: Revert to a snapshot
  vmware_guest_snapshot:
    hostname: 192.168.1.209
    username: administrator@vsphere.local
    password: vmware
    datacenter: datacenter_name
    folder: /myfolder
    name: dummy_vm
    state: revert
    snapshot_name: snap1
  delegate_to: localhost
